openapi: 3.0.0
info:
  title: To-Do List API
  description: API for managing a to-do list.
  version: 1.0.0
paths:
  /todos:
    post:
      summary: Create a new to-do item
      description: This endpoint creates a new to-do item.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Buy groceries"
                description:
                  type: string
                  example: "Milk, Bread, Butter, Eggs"
                due_date:
                  type: string
                  format: date
                  example: "2023-07-10"
            examples:
              todoExample1:
                value:
                  title: "Finish homework"
                  description: "Math, Science, English"
                  due_date: "2023-07-15"
              todoExample2:
                value:
                  title: "Clean the house"
                  description: "Living room, Kitchen, Bathroom"
                  due_date: "2023-07-12"
              todoExample3:
                value:
                  title: "Prepare presentation"
                  description: "Slides, Notes, Handouts"
                  due_date: "2023-07-20"
      responses:
        '201':
          description: To-do item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  title:
                    type: string
                    example: "Buy groceries"
                  description:
                    type: string
                    example: "Milk, Bread, Butter, Eggs"
                  due_date:
                    type: string
                    format: date
                    example: "2023-07-10"
              examples:
                successResponse1:
                  value:
                    id: "1"
                    title: "Finish homework"
                    description: "Math, Science, English"
                    due_date: "2023-07-15"
                successResponse2:
                  value:
                    id: "2"
                    title: "Clean the house"
                    description: "Living room, Kitchen, Bathroom"
                    due_date: "2023-07-12"
                successResponse3:
                  value:
                    id: "3"
                    title: "Prepare presentation"
                    description: "Slides, Notes, Handouts"
                    due_date: "2023-07-20"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"
              examples:
                errorResponse1:
                  value:
                    error: "Title is required"
                errorResponse2:
                  value:
                    error: "Due date must be a valid date"
                errorResponse3:
                  value:
                    error: "Description cannot be empty"

components:
  schemas:
    ToDoItem:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, Bread, Butter, Eggs"
        due_date:
          type: string
          format: date
          example: "2023-07-10"
